version: '3'
services:
  web:
    build: .
    command: python /project_ministerstvo_strizhek/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/project_ministerstvo_strizhek
    ports:
      - 8000:8000
    depends_on:
      - db
      - cache

  db:
    image: 'postgres:13.0-alpine'
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: postgres
        POSTGRES_DB: main_db
    ports:
       - "127.0.0.1:5432:5432" 
  
  cache:
    image: 'bitnami/memcached:latest'
    ports:
     - "11211:11211"


volumes:
  postgres_data: